default_language_version:
    python: python3.8
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-ast
    -   id: check-case-conflict
    -   id: debug-statements
        exclude: 'fixes/shortcuts/__init__.py'
    -   id: name-tests-test
        args: [--django]
        exclude: 'runner.py'
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.24.0
    hooks:
    -   id: pyupgrade
        args: ['--py38-plus']
-   repo: https://github.com/axiros/axblack
    rev: v2020.11.12
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    - id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'
    hooks:
    - id: bandit
      args: ['--ini=.bandit','-ll']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-django',
          'flake8-todos',
          'flake8-use-fstring',
          'pep8-naming',
      ]
